# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import images

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(281, 274)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 271, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.browse_edit = QtWidgets.QLineEdit(self.tab)
        self.browse_edit.setEnabled(False)
        self.browse_edit.setGeometry(QtCore.QRect(7, 10, 171, 20))
        self.browse_edit.setObjectName("browse_edit")
        self.browse_cb = QtWidgets.QCheckBox(self.tab)
        self.browse_cb.setGeometry(QtCore.QRect(187, 10, 16, 21))
        self.browse_cb.setText("")
        self.browse_cb.setObjectName("browse_cb")
        self.browse_button = QtWidgets.QPushButton(self.tab)
        self.browse_button.setEnabled(False)
        self.browse_button.setGeometry(QtCore.QRect(210, 9, 51, 23))
        self.browse_button.setObjectName("browse_button")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 47, 121, 21))
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.job_num_edit = QtWidgets.QLineEdit(self.tab)
        self.job_num_edit.setGeometry(QtCore.QRect(140, 47, 111, 21))
        self.job_num_edit.setObjectName("job_num_edit")
        self.separator_edit = QtWidgets.QLineEdit(self.tab)
        self.separator_edit.setGeometry(QtCore.QRect(140, 70, 111, 21))
        self.separator_edit.setObjectName("separator_edit")
        self.dialog_label = QtWidgets.QLabel(self.tab)
        self.dialog_label.setEnabled(True)
        self.dialog_label.setGeometry(QtCore.QRect(10, 100, 241, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.dialog_label.setPalette(palette)
        self.dialog_label.setStyleSheet("background-color:rgb(0, 0, 255);")
        self.dialog_label.setTextFormat(QtCore.Qt.RichText)
        self.dialog_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dialog_label.setWordWrap(True)
        self.dialog_label.setIndent(3)
        self.dialog_label.setObjectName("dialog_label")
        self.ok_button = QtWidgets.QPushButton(self.tab)
        self.ok_button.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.go_button = QtWidgets.QPushButton(self.tab)
        self.go_button.setEnabled(False)
        self.go_button.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.go_button.setObjectName("go_button")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lock_unlocked_pb = QtWidgets.QPushButton(self.tab)
        self.lock_unlocked_pb.setEnabled(False)
        self.lock_unlocked_pb.setGeometry(QtCore.QRect(120, 160, 31, 23))
        self.lock_unlocked_pb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/locked/ic_lock_black_24dp_2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/unlocked/ic_lock_open_black_24dp_2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.lock_unlocked_pb.setIcon(icon)
        self.lock_unlocked_pb.setObjectName("lock_unlocked_pb")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.browse_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.browse_button_2.setEnabled(True)
        self.browse_button_2.setGeometry(QtCore.QRect(210, 10, 51, 21))
        self.browse_button_2.setObjectName("browse_button_2")
        self.browse_edit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.browse_edit_2.setEnabled(False)
        self.browse_edit_2.setGeometry(QtCore.QRect(10, 11, 181, 20))
        self.browse_edit_2.setObjectName("browse_edit_2")
        self.dialog_label_2 = QtWidgets.QLabel(self.tab_2)
        self.dialog_label_2.setGeometry(QtCore.QRect(10, 41, 241, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.dialog_label_2.setPalette(palette)
        self.dialog_label_2.setStyleSheet("background-color:rgb(0, 0, 255);")
        self.dialog_label_2.setTextFormat(QtCore.Qt.RichText)
        self.dialog_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dialog_label_2.setWordWrap(True)
        self.dialog_label_2.setIndent(3)
        self.dialog_label_2.setObjectName("dialog_label_2")
        self.go_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.go_button_2.setEnabled(False)
        self.go_button_2.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.go_button_2.setObjectName("go_button_2")
        self.ok_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.ok_button_2.setEnabled(False)
        self.ok_button_2.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.ok_button_2.setObjectName("ok_button_2")
        self.browse_edit_2.raise_()
        self.browse_button_2.raise_()
        self.dialog_label_2.raise_()
        self.go_button_2.raise_()
        self.ok_button_2.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHow_to_use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionHow_to_use)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UberTools"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Job #(last 5 digits)"))
        self.dialog_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Fill your information and then click \'OK!\'</span></p></body></html>"))
        self.ok_button.setText(_translate("MainWindow", "OK!"))
        self.go_button.setText(_translate("MainWindow", "Go!"))
        self.label_2.setText(_translate("MainWindow", "Car Label( \'-\' for simplex)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "UberTitle"))
        self.browse_button_2.setText(_translate("MainWindow", "Browse"))
        self.dialog_label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Click \'Browse\' to locate the folder where the drawings are located. </span></p></body></html>"))
        self.go_button_2.setText(_translate("MainWindow", "Go!"))
        self.ok_button_2.setText(_translate("MainWindow", "OK!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Wblock"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionHow_to_use.setText(_translate("MainWindow", "How to use..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))

